dropout: 0.1
epochs: 2000
hid_dim: 64
lr: 0.001
model_name: NeuroPath
nlayers: 1
patience: 5
ratio_fc: 0.2
ratio_sc: 0.2
reduce: mean
split_args:
  test_size: 0.2
  train_size: 0.6
  valid_size: 0.2
use_wandb: true
wd: 0.01